問題に難易度表示機能を実装する。
makutamoto/mojacoder pull request #115
Opened 2021-01-28 14:00 UTC by magurofly

#113
まずはproblems.jsonから読み込んでgraphqlに保存するところまでをやろうとしています。
よくわかっていないので、バグがあると思います。

2021-01-28 14:21 UTC, makutamoto commented
これはとりあえずバックエンドのみ変更してみるということですか？

2021-01-28 15:10 UTC, magurofly commented
このプルリクでフロントエンドをやることまで視野に入れていますが、まずバックエンドのバグがあったら困るのでこのコミットまでをpushしました

2021-01-28 15:12 UTC, makutamoto commented
問題なさそうだったら放置でよろしいでしょうか。

2021-01-28 15:17 UTC, magurofly commented
はい

2021-02-24 16:50 UTC, magurofly commented
とりあえずエラーが出てたところを修正した
まだ使えるかはわかってない（たぶんできない）

2021-02-24 16:54 UTC, makutamoto requested changes
とりあえず直してほしいところです。

2021-02-24 16:54 UTC, makutamoto commented on mojacoder-backend/lambda/s3-posted-problems-created-notification/index.ts
> +                    BOOL: problem.difficulty !== null,
!== undefinedだと思います

2021-02-24 16:54 UTC, makutamoto commented on mojacoder-backend/lambda/s3-posted-problems-created-notification/index.ts
> +                                BOOL: problem.difficulty !== null,
ここも

2021-02-24 16:54 UTC, makutamoto commented on mojacoder-frontend/pages/problems/index.tsx
> +                                        <Difficulty>{item.difficulty}</Difficulty>
`<Difficulty />`のあとに`{' '}`がないと●Problemとなって気持ち悪い気がします。

2021-02-24 16:55 UTC, makutamoto commented on mojacoder-backend/lambda/s3-posted-problems-created-notification/index.ts
> +                    BOOL: problem.difficulty !== null,
{} = JSON.parse()は存在しなかった時にundefinedになるので。

2021-02-24 17:08 UTC, magurofly commented on mojacoder-frontend/pages/problems/index.tsx
> +                                        <Difficulty>{item.difficulty}</Difficulty>
これは
`<span><Difficulty>{item.difficulty}</Difficulty>{' '}</span>`
みたいな意味ですか？

2021-02-24 17:12 UTC, magurofly commented on mojacoder-frontend/pages/problems/index.tsx
> +                                        <Difficulty>{item.difficulty}</Difficulty>
それとも`<Difficulty />`の内部でスペースを入れますか？
Difficultyの内部で解決する方が綺麗な気がします

2021-02-24 17:15 UTC, makutamoto commented on mojacoder-frontend/pages/problems/index.tsx
> +                                        <Difficulty>{item.difficulty}</Difficulty>
```jsx
<>
    <Difficulty>{item.difficulty}</Difficulty>
    {' '}
</>
```
です。
<>はReact.Fragmentという要素です。

2021-02-24 17:15 UTC, makutamoto commented on mojacoder-frontend/pages/problems/index.tsx
> +                                        <Difficulty>{item.difficulty}</Difficulty>
DifficultyにDifficulty表示以外の機能（レイアウトなど）を入れると気持ち悪い気がします。

2021-02-24 17:17 UTC, magurofly commented on mojacoder-backend/lambda/s3-posted-problems-created-notification/index.ts
> +                    BOOL: problem.difficulty !== null,
(1) これは型としては`string | null`ですが、`!== undefined`で大丈夫ですか？
先程、`!= null`がよいという記事を見ました
(2) また、`difficulty`の型に`string | null`を割り当てるのが良いかわかりません
difficultyは未定義の場合があるはずなので、`| null`をつけたのですが、これが良いかです
TypeScriptに詳しいmakutamotoさんお願いします

2021-02-24 17:36 UTC, makutamoto commented on mojacoder-backend/lambda/s3-posted-problems-created-notification/index.ts
> +    const { title, difficulty } = JSON.parse(await configFile.async("string")) as Config;
この後に
```javascript
if(!difficulty) difficulty = null
```
を入れて未定義の場合をnullにしてしまいましょう。

2021-02-24 17:36 UTC, makutamoto commented on mojacoder-backend/lambda/s3-posted-problems-created-notification/index.ts
> +                    BOOL: problem.difficulty !== null,
確かに`!== null`のほうが気持ちいいので変更箇所を変えます。

(1)
`difficulty`に代入されうる値は`null`ではなく`undefined`だと思います。
※Javascriptで`null`と`undefined`は異なった値です。!=ではそれを区別できないため!==を使用します。

(2)
(1)より、実際のdifficultyの型は`string | undefined`です。

2021-02-24 18:14 UTC, magurofly commented on mojacoder-backend/lambda/s3-posted-problems-created-notification/index.ts
> +    const { title, difficulty } = JSON.parse(await configFile.async("string")) as Config;
`difficulty`が`const`なので、
```TypeScript
    return {
        title,
        statement,
        editorial,
        difficulty ?? null,
```
とするのはいかがでしょう

2021-02-24 18:16 UTC, makutamoto commented on mojacoder-backend/lambda/s3-posted-problems-created-notification/index.ts
> +    const { title, difficulty } = JSON.parse(await configFile.async("string")) as Config;
そっちのほうがいいですね！そうしましょう！

2021-02-24 19:44 UTC, magurofly commented on mojacoder-frontend/pages/problems/index.tsx
> +                                        <Difficulty>{item.difficulty}</Difficulty>
OK!

2021-02-24 19:45 UTC, magurofly commented on mojacoder-backend/lambda/s3-posted-problems-created-notification/index.ts
> +    const { title, difficulty } = JSON.parse(await configFile.async("string")) as Config;
了解
※`Config`の`difficulty`は`string | undefined`にしました

2021-02-24 19:49 UTC, makutamoto approved these changes

2021-02-24 19:50 UTC, merged

2021-02-25 03:45 UTC, magurofly commented
よく見たら、XSS対策全然してなかったので、後で直します