問題エディタで難易度を変更できるようにする
makutamoto/mojacoder pull request #117
Opened 2021-02-25 03:59 UTC by magurofly

問題エディターに難易度選択を追加

2021-03-04 15:14 UTC, makutamoto commented
もしかしてこのプルリクって完成してたりします？

2021-03-05 15:37 UTC, magurofly commented
してるかも？

2021-03-06 03:52 UTC, makutamoto requested changes

2021-03-06 03:52 UTC, makutamoto commented on mojacoder-frontend/containers/ProblemEditor.tsx
> +                difficulty: problemDifficulty,
Difficultyの選択を`-`にした時に`problem.json`に`-`が入るのが気持ち悪いですね。
Difficulty未選択のときは`diffficulty`プロパティを削除してください。

2021-03-07 05:57 UTC, magurofly commented on mojacoder-frontend/containers/ProblemEditor.tsx
> +                difficulty: problemDifficulty,
おけ

2021-03-07 07:18 UTC, magurofly commented on mojacoder-frontend/containers/ProblemEditor.tsx
> +                difficulty: problemDifficulty,
```HTML
<option value="none">-</option>
```

```TypeScript
difficulty: problemDifficulty == 'none' ? undefined : problemDifficulty,
```

`undefined`にすると`JSON.stringify`で無視されるのでそうしました

2021-03-07 07:20 UTC, makutamoto approved these changes

2021-03-07 07:41 UTC, merged

2021-03-07 07:42 UTC, magurofly commented
え、failureでしたが大丈夫ですか？

2021-03-07 07:42 UTC, makutamoto commented
エラーが出ていますが、多分大丈夫だと思うのでマージしました。

2021-03-07 07:42 UTC, makutamoto commented
faillureの原因はAPIへのリンクを変更したからです。

2021-03-07 07:43 UTC, makutamoto commented
Rebaseを要求しようかと思いましたがめんどくさいのでマージしました。

2021-03-07 07:45 UTC, makutamoto commented
正常に動いてますね。よかった！